"""Initial migration

Revision ID: 10ad2ab0a723
Revises: None
Create Date: 2026-06-26 17:58:03.934505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = '10ad2ab0a723'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (v4).'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address.'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Bcrypt hashed password.'),
    sa.Column('role', sa.Enum('STUDENT', 'COUNSELOR', 'ADMIN', name='user_role'), nullable=False, comment="User role permissions ('STUDENT', 'COUNSELOR', 'ADMIN')."),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Soft delete toggle.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Account creation time.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (v4).'),
    sa.Column('student_id', sa.Uuid(), nullable=False, comment='References USERS(id).'),
    sa.Column('mental_wellness_score', sa.Float(), nullable=False, comment='Calculated well-being metric (0.0 to 100.0).'),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risk_level'), nullable=False, comment="Assessed risk level ('LOW', 'MEDIUM', 'HIGH')."),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of evaluation completion.'),
    sa.CheckConstraint('mental_wellness_score >= 0.0 AND mental_wellness_score <= 100.0', name='chk_mental_wellness_score'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assessments_student_risk', 'assessments', ['student_id', 'risk_level'], unique=False)
    op.create_index(op.f('ix_assessments_evaluated_at'), 'assessments', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_index(op.f('ix_assessments_student_id'), 'assessments', ['student_id'], unique=False)
    op.create_table('mood_logs',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (v4).'),
    sa.Column('student_id', sa.Uuid(), nullable=False, comment='References USERS(id).'),
    sa.Column('input_type', sa.Enum('TEXT', 'VOICE', 'SURVEY', name='input_type'), nullable=False, comment='Type of input: TEXT, VOICE, or SURVEY.'),
    sa.Column('raw_content', sa.Text(), nullable=True, comment='The actual journal entry text or transcript.'),
    sa.Column('self_reported_score', sa.Integer(), nullable=True, comment='Subjective mental score (1 to 10).'),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp of journal submission.'),
    sa.CheckConstraint('self_reported_score >= 1 AND self_reported_score <= 10', name='chk_self_reported_score'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mood_logs_student_date', 'mood_logs', ['student_id', sa.literal_column('logged_at DESC')], unique=False)
    op.create_index(op.f('ix_mood_logs_id'), 'mood_logs', ['id'], unique=False)
    op.create_index(op.f('ix_mood_logs_logged_at'), 'mood_logs', ['logged_at'], unique=False)
    op.create_index(op.f('ix_mood_logs_student_id'), 'mood_logs', ['student_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (v4).'),
    sa.Column('assessment_id', sa.Uuid(), nullable=False, comment='References ASSESSMENTS(id) uniquely.'),
    sa.Column('student_id', sa.Uuid(), nullable=False, comment='References USERS(id) for the student who triggered the alert.'),
    sa.Column('counselor_id', sa.Uuid(), nullable=True, comment='References USERS(id) for the counselor assigned to resolve the alert. Nullable if unassigned.'),
    sa.Column('status', sa.Enum('PENDING', 'REVIEWED', 'RESOLVED', name='alert_status'), nullable=False, comment="Current workflow status of the alert ('PENDING', 'REVIEWED', 'RESOLVED')."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp indicating when the alert was triggered.'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp indicating when the counselor closed and resolved the alert.'),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_status_counselor', 'alerts', ['status', 'counselor_id'], unique=False)
    op.create_index(op.f('ix_alerts_assessment_id'), 'alerts', ['assessment_id'], unique=True)
    op.create_index(op.f('ix_alerts_counselor_id'), 'alerts', ['counselor_id'], unique=False)
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_student_id'), 'alerts', ['student_id'], unique=False)
    op.create_table('emotion_analyses',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier (v4).'),
    sa.Column('mood_log_id', sa.Uuid(), nullable=False, comment='References MOOD_LOGS(id) uniquely.'),
    sa.Column('detected_emotions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment="Matrix of emotions (e.g. {'joy': 0.1, 'sadness': 0.8})."),
    sa.Column('sentiment_score', sa.Float(), nullable=False, comment='Aggregate NLP polarity score (-1.0 to 1.0).'),
    sa.Column('primary_emotion', sa.String(length=50), nullable=False, comment='Dominant extracted emotion.'),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='ML inference completion timestamp.'),
    sa.CheckConstraint('sentiment_score >= -1.0 AND sentiment_score <= 1.0', name='chk_sentiment_score'),
    sa.ForeignKeyConstraint(['mood_log_id'], ['mood_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_emotions_jsonb', 'emotion_analyses', ['detected_emotions'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_emotion_analyses_id'), 'emotion_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_emotion_analyses_mood_log_id'), 'emotion_analyses', ['mood_log_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emotion_analyses_mood_log_id'), table_name='emotion_analyses')
    op.drop_index(op.f('ix_emotion_analyses_id'), table_name='emotion_analyses')
    op.drop_index('idx_emotions_jsonb', table_name='emotion_analyses', postgresql_using='gin')
    op.drop_table('emotion_analyses')
    op.drop_index(op.f('ix_alerts_student_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_counselor_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_assessment_id'), table_name='alerts')
    op.drop_index('idx_alerts_status_counselor', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_mood_logs_student_id'), table_name='mood_logs')
    op.drop_index(op.f('ix_mood_logs_logged_at'), table_name='mood_logs')
    op.drop_index(op.f('ix_mood_logs_id'), table_name='mood_logs')
    op.drop_index('idx_mood_logs_student_date', table_name='mood_logs')
    op.drop_table('mood_logs')
    op.drop_index(op.f('ix_assessments_student_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_index(op.f('ix_assessments_evaluated_at'), table_name='assessments')
    op.drop_index('idx_assessments_student_risk', table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
